import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { api, fmtDate, fmtNum, fmtVND, getToken } from '../api.js';
import { useMeta } from '../meta.jsx';
import { useAuth } from '../auth.jsx';
import StatusBadge from '../components/StatusBadge.jsx';
import BulkDeleteButton from '../components/BulkDeleteButton.jsx';

export default function Orders() {
  const { states } = useMeta(); const { user } = useAuth(); const nav = useNavigate();
  const canWrite = ['admin', 'purchasing'].includes(user.role); const isAdmin = user.role === 'admin';
  const [rows, setRows] = useState([]); const [teams, setTeams] = useState([]); const [suppliers, setSuppliers] = useState([]); const [advanced, setAdvanced] = useState(false);
  const [filters, setFilters] = useState({ q: '', status: '', team_id: '', supplier_id: '', date_from: '', date_to: '', date_field: 'request_date', quick: '' }); const [view, setView] = useState('list'); const [err, setErr] = useState('');
  const set = (key, value) => setFilters((old) => ({ ...old, [key]: value }));
  const load = () => { const p = new URLSearchParams({ q: filters.q, status: filters.status, team_id: filters.team_id, supplier_id: filters.supplier_id, date_field: filters.date_field, limit: '100' }); if (filters.date_from) p.set('date_from', filters.date_from); if (filters.date_to) p.set('date_to', filters.date_to); api.get(`/orders?${p}`).then((r) => setRows(r.data || [])).catch((e) => setErr(e.message)); };
  useEffect(() => { load(); }, [filters.q, filters.status, filters.team_id, filters.supplier_id, filters.date_from, filters.date_to, filters.date_field]);
  useEffect(() => { api.get('/teams?limit=200').then((r) => setTeams(r.data || [])); api.get('/suppliers?limit=500').then((r) => setSuppliers(r.data || [])); }, []);
  const visible = useMemo(() => rows.filter((row) => filters.quick === 'needs_attention' ? ['new', 'in_progress', 'pending_confirmation'].includes(row.status) : filters.quick === 'has_warning' ? !row.supplier_name || !Number(row.item_count) : true), [rows, filters.quick]);
  const clear = () => setFilters({ q: '', status: '', team_id: '', supplier_id: '', date_from: '', date_to: '', date_field: 'request_date', quick: '' });
  const download = async (format) => { const res = await fetch(`/api/orders/export?format=${format}`, { headers: { Authorization: `Bearer ${getToken()}` } }); const url = URL.createObjectURL(await res.blob()); const a = document.createElement('a'); a.href = url; a.download = `procureos-orders.${format}`; a.click(); URL.revokeObjectURL(url); };
  const removeOrder = async (order, event) => { event?.stopPropagation(); if (!confirm(`Xóa đơn hàng ${order.order_code}? (xóa mềm, có thể khôi phục)`)) return; try { await api.del(`/orders/${order.id}`); load(); } catch (e) { setErr(e.message); } };
  const orderRow = (o) => <tr key={o.id} onClick={() => nav(`/orders/${o.id}`)} style={{ cursor: 'pointer' }}>
    <td className="orders-primary"><strong>{o.order_code}</strong><span title={o.project_name}>{o.project_name || '-'}</span></td>
    <td><span>{o.team_name || '-'}</span><span className="orders-cell-meta" title={o.supplier_name}>{o.supplier_name || 'Chưa chọn NCC'}</span></td>
    <td><span>{fmtDate(o.expected_date || o.request_date)}</span><span className="orders-cell-meta">{fmtNum(o.item_count)} dòng hàng</span></td>
    <td className="r"><strong>{fmtVND(o.total_amount)}</strong></td>
    <td className="orders-status-cell"><StatusBadge code={o.status} /></td>
    <td className="orders-open"><button className="btn-sm" onClick={(e) => { e.stopPropagation(); nav(`/orders/${o.id}`); }}>Mở</button>{isAdmin && <button className="btn-sm btn-danger" title={`Xóa ${o.order_code}`} onClick={(e) => removeOrder(o, e)}>Xóa</button>}</td>
  </tr>;
  return <><div className="topbar"><h1>Đơn hàng</h1>{canWrite && <button className="btn-primary" onClick={() => nav('/orders/new')}>+ Tạo đơn mới</button>}</div><div className="content">
    <div className="orders-controls"><div className="orders-filterbar"><input className="search" placeholder="Mã đơn, dự án, người yêu cầu…" value={filters.q} onChange={(e) => set('q', e.target.value)} /><select value={filters.status} onChange={(e) => set('status', e.target.value)}><option value="">Tất cả trạng thái</option>{states.map((s) => <option key={s.code} value={s.code}>{s.name}</option>)}</select><button className="btn-sm" onClick={() => setAdvanced(!advanced)} aria-expanded={advanced}>Bộ lọc {advanced ? '▴' : '▾'}</button><span className="spacer" /><select value={view} onChange={(e) => setView(e.target.value)} title="Chế độ xem"><option value="list">Danh sách</option><option value="status">Nhóm trạng thái</option><option value="kanban">Kanban</option></select></div>
    {advanced && <div className="orders-filtermore"><select value={filters.team_id} onChange={(e) => set('team_id', e.target.value)}><option value="">Tất cả team</option>{teams.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={filters.supplier_id} onChange={(e) => set('supplier_id', e.target.value)}><option value="">Tất cả NCC</option>{suppliers.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={filters.date_field} onChange={(e) => set('date_field', e.target.value)}><option value="request_date">Ngày YC</option><option value="expected_date">Hạn nhận</option><option value="created_at">Ngày tạo</option></select><input type="date" aria-label="Từ ngày" value={filters.date_from} onChange={(e) => set('date_from', e.target.value)} /><input type="date" aria-label="Đến ngày" value={filters.date_to} onChange={(e) => set('date_to', e.target.value)} /><button className="btn-sm" onClick={clear}>Reset</button></div>}
    <div className="orders-actions"><button className={filters.quick === 'needs_attention' ? 'btn-primary btn-sm' : 'btn-sm'} onClick={() => set('quick', filters.quick === 'needs_attention' ? '' : 'needs_attention')}>Cần xử lý</button><button className={filters.quick === 'has_warning' ? 'btn-primary btn-sm' : 'btn-sm'} onClick={() => set('quick', filters.quick === 'has_warning' ? '' : 'has_warning')}>Có cảnh báo</button><span className="muted">{visible.length} đơn</span><span className="spacer" /><button className="btn-sm" onClick={() => download('xlsx')}>Excel</button><button className="btn-sm" onClick={() => download('csv')}>CSV</button>{isAdmin && <BulkDeleteButton entity="đơn hàng" countPath="/orders/count" deletePath="/orders" onDone={load} />}</div></div>
    {err && <div className="error">{err}</div>}
    {view === 'kanban' ? <div className="orders-kanban">{states.map((state) => { const group = visible.filter((o) => o.status === state.code); return <section className="orders-lane" key={state.code}><div className="orders-lane-head"><StatusBadge code={state.code} /><span>{group.length}</span></div>{group.slice(0, 25).map((o) => <article className="orders-card" key={o.id} onClick={() => nav(`/orders/${o.id}`)}><strong>{o.order_code}</strong><div>{o.project_name || '-'}</div><small>{o.supplier_name || 'Chưa chọn NCC'}</small><div className="orders-card-meta"><span>{fmtVND(o.total_amount)}</span><span>{fmtDate(o.expected_date || o.request_date)}</span></div><small>{o.item_count || 0} dòng</small></article>)}{group.length > 25 && <div className="muted">+{group.length - 25} đơn khác</div>}</section>; })}</div> : view === 'status' ? <div>{states.map((state) => { const group = visible.filter((o) => o.status === state.code); return group.length ? <section className="card" key={state.code} style={{ marginBottom: 10, padding: 0 }}><div style={{ padding: '10px 12px' }}><strong>{state.name}</strong><span className="muted"> · {group.length} đơn</span></div><div className="table-wrap" style={{ border: 'none' }}><table className="orders-table"><tbody>{group.map(orderRow)}</tbody></table></div></section> : null; })}</div> : <div className="table-wrap"><table className="orders-table"><thead><tr><th>Đơn hàng / dự án</th><th>Team / NCC</th><th>Hạn nhận / dòng</th><th className="r">Giá trị</th><th>Trạng thái</th><th /></tr></thead><tbody>{visible.map(orderRow)}{!visible.length && <tr><td colSpan={6} className="center-msg">Không có đơn hàng phù hợp</td></tr>}</tbody></table></div>}
  </div></>;
}
