import { useMemo, useState } from 'react';
import { api } from '../api.js';

const initialWeights = { total_cost: 45, unit_price: 25, delivery: 15, reputation: 10, commercial_terms: 5 };
const labels = { total_cost: 'Tổng chi phí', unit_price: 'Đơn giá', delivery: 'Giao hàng', reputation: 'Uy tín NCC', commercial_terms: 'Điều khoản' };
const money = (value) => value === null || value === undefined ? '—' : new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 }).format(value);
async function encode(file) { const bytes = new Uint8Array(await file.arrayBuffer()); let text = ''; for (let i = 0; i < bytes.length; i += 0x8000) text += String.fromCharCode(...bytes.subarray(i, i + 0x8000)); return btoa(text); }

export default function QuoteComparison() {
  const [files, setFiles] = useState([]); const [weights, setWeights] = useState(initialWeights); const [result, setResult] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const selected = useMemo(() => new Map(files.map((entry) => [entry.id, entry])), [files]);
  const choose = (event) => { const next = [...event.target.files].slice(0, 3).map((file, index) => ({ id: `${Date.now()}-${index}`, file, url: URL.createObjectURL(file) })); setFiles(next); setResult(null); setError(''); event.target.value = ''; };
  const compare = async () => {
    if (!files.length) return setError('Chọn từ 1 đến 3 báo giá để so sánh.');
    setBusy(true); setError('');
    try { const payload = await Promise.all(files.map(async (entry) => ({ client_id: entry.id, filename: entry.file.name, data_base64: await encode(entry.file) }))); setResult(await api.post('/quotation-extractions/compare', { files: payload, weights })); }
    catch (e) { setError(e.message || 'Không thể so sánh báo giá.'); } finally { setBusy(false); }
  };
  const comparison = result?.comparison;
  return <><div className="topbar"><h1>So sánh báo giá</h1><span className="muted">Tối đa 3 báo giá độc lập; AI chỉ tư vấn.</span></div><div className="content">
    <div className="card"><div className="field"><label>Chọn báo giá (tối đa 5 MB/file)</label><input type="file" multiple accept=".xls,.xlsx,.csv,.pdf,.doc,.docx,.png,.jpg,.jpeg,.webp" onChange={choose} /></div>{files.length > 0 && <div className="row" style={{ flexWrap: 'wrap', gap: 10, margin: '8px 0' }}>{files.map((entry) => <span key={entry.id} className="badge">{entry.file.name} · <a href={entry.url} target="_blank" rel="noreferrer">Xem/Tải</a></span>)}</div>}<h3>Trọng số đánh giá</h3><div className="grid" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(150px,1fr))' }}>{Object.entries(weights).map(([key, value]) => <div className="field" key={key}><label>{labels[key]} (%)</label><input type="number" min="0" max="100" value={value} onChange={(e) => setWeights({ ...weights, [key]: e.target.value })} /></div>)}</div>{error && <div className="error">{error}</div>}<button className="btn-primary" disabled={busy} onClick={compare}>{busy ? 'Đang trích xuất và so sánh…' : 'So sánh bằng AI'}</button></div>
    {result?.extraction?.files?.some((file) => file.status === 'error') && <div className="card"><strong>File không thể đọc</strong>{result.extraction.files.filter((file) => file.status === 'error').map((file) => <div key={file.client_id}>{file.filename}: {file.error}</div>)}</div>}
    {comparison && <><div className="card"><h2 style={{ marginTop: 0 }}>Khuyến nghị {comparison.mode === 'ai' ? 'AI' : comparison.mode === 'demo-rule-based' ? 'demo/parser (không phải AI thật)' : 'theo quy tắc'}</h2><strong>{comparison.recommendation?.reason}</strong>{comparison.recommendation?.warnings?.map((warning, i) => <div key={i} className="muted">⚠ {warning}</div>)}<div className="muted" style={{ marginTop: 8 }}>AI không tự tạo hoặc sửa đơn hàng. Hãy kiểm tra và xác nhận trước khi áp dụng vào đơn hàng.</div></div><div className="card table-wrap"><h2>Điểm tổng hợp theo báo giá</h2><table><thead><tr><th>File / NCC</th><th>Trước VAT</th><th>VAT</th><th>Sau VAT</th><th>Uy tín / lịch sử</th><th>Điểm</th><th>Nguồn</th></tr></thead><tbody>{comparison.quotes.map((quote) => <tr key={quote.quote_id}><td>{quote.source_file.filename}<br /><span className="muted">{quote.supplier_name || 'Chưa nhận diện NCC'}</span></td><td>{money(quote.total_before_vat)}</td><td>{money(quote.total_vat)}</td><td>{money(quote.total_after_vat)}</td><td>{quote.purchase_count || 0} lần mua</td><td><strong>{quote.scores?.total ?? '—'}/100</strong></td><td>{selected.get(quote.quote_id) && <a href={selected.get(quote.quote_id).url} target="_blank" rel="noreferrer">Xem/Tải</a>}</td></tr>)}</tbody></table></div><div className="card table-wrap"><h2>So sánh từng mặt hàng</h2><table><thead><tr><th>Mặt hàng</th>{comparison.quotes.map((quote) => <th key={quote.quote_id}>{quote.supplier_name || quote.source_file.filename}</th>)}</tr></thead><tbody>{comparison.rows.map((row) => <tr key={row.item_key}><td>{row.item_name}</td>{row.quotes.map((quote) => <td key={quote.quote_id}>{quote.missing ? <span className="muted">Không khớp</span> : <>{quote.quantity || '—'} × {money(quote.unit_price)}<br /><span className="muted">VAT {quote.vat_percent ?? '—'}% · {money(quote.total_after_vat)}</span>{quote.issues?.length > 0 && <div className="error">{quote.issues.join(', ')}</div>}</>}</td>)}</tr>)}</tbody></table></div>{comparison.warnings?.length > 0 && <div className="card"><h3>Cảnh báo dữ liệu</h3>{comparison.warnings.map((warning, i) => <div key={i}>⚠ {warning}</div>)}</div>}</>}
  </div></>;
}
